### ISSUE TITLE
Question: Revealing data on end instead of start

### ISSUE THREAD

**Issue by Ni3verma** [Skyyo/compose-swipe-to-reveal#2]
Hi, for my project I want to use your code but only change that i wanted was to implement **end to start** drag.
So what changes do I need to do to achieve this?

I am able to place the icon towards end, but this is appearing if I drag start to end. Not sure how to achieve the opposite, I guess I need to revert some signs of offsetX. Need your help 

![image](https://user-images.githubusercontent.com/20037625/132899302-07d51269-faa5-483c-9f14-ee7d8ebc25f5.png)

**Comment by Skyyo** [comment]
@Ni3verma I've pushed a new branch which should help with your requirements, please take a look and do adjustments from there. It gives a general idea and should be enough.

https://github.com/Skyyo/compose-swipe-to-reveal/tree/rtl_prototype

**Comment by Ni3verma** [comment]
Thanks for your quick help @Skyyo 
There is only one problem, even if I drag start to end. card is sliding end to start. any idea how to stop that?

**Comment by Skyyo** [comment]
Yeap. Log what's happening and adjust the code further, to prevent the
unwanted behaviour

**Comment by Ni3verma** [comment]
Hey I modified the code as below and it is working as expected, let me know if you see any issue with this simpler approach:
```
const val MIN_DRAG = 10
pointerInput(Unit) {
                detectHorizontalDragGestures { _, dragAmount ->
                    if (dragAmount <= -MIN_DRAG) {
                        onExpand()
                    } else if (dragAmount > MIN_DRAG) {
                        onCollapse()
                    }
                }
            }
```

**Comment by Skyyo** [comment]
Can't think of any issues unless feature specifications will require more math involved. For simple cases this looks simple & great, so good job @Ni3verma
