### ISSUE TITLE
How to make sure only one tile is open at a time?

### ISSUE THREAD

**Issue by himanshu-my** [Skyyo/compose-swipe-to-reveal#3]
I want to reveal only one tile at time. If user reveal other time the previously revealed tile should close automatically.

**Comment by Skyyo** [comment]
this is not an issue with the code in the repo, so closing.

@himanshu-my you have to use single id instead of list of ids, and simply change it whenever new item is swiped, reactiveness will do rest of the work.

**Comment by himanshu-my** [comment]
Thanks a ton @Skyyo. now it works for me.
